routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes([
    'register' => false,
    'reset'    => false,
    'verify'   => false
]);

Route::group(['middleware' => ['auth']], function() {
    // Product
    Route::get('product/json', 'ProductController@json');
    Route::get('product/import-{import}', 'ProductController@import')->name('product.import');
    Route::resource('product', 'ProductController');

    // Franchise
    Route::resource('franchise', 'FranchiseController');

    // Import
    Route::resource('import', 'ImportController');

    // Shop
    Route::get('shop', 'ShopController@index')->name('shop.index');
    Route::get('shop/json', 'ShopController@json')->name('product.json');
    Route::resource('shop', 'ShopController');

    // Device
    Route::get('device', 'DeviceController@index')->name('device.index');
    Route::resource('device', 'DeviceController');



    Route::group(['middleware' => ['checkReport']], function() {
        // Report
        Route::get('report/order', 'ReportController@order')->name('report.order');
        Route::get('report/shift', 'ReportController@shift')->name('report.shift');
        Route::get('report/shift-user', 'ReportController@shiftUser')->name('report.shift-user');
        Route::get('report/shift-plan', 'ReportController@shiftPlan')->name('report.shift-plan');
        Route::get('report/reject', 'ReportController@reject')->name('report.reject');
        Route::get('report/quality', 'ReportController@quality')->name('report.quality');
        Route::get('report/inventory', 'ReportController@inventory')->name('report.inventory');
        Route::get('report/inventory-kitchen', 'ReportController@inventoryKitchen')->name('report.inventory-kitchen');
        Route::get('report/inventory-diff', 'ReportController@inventoryDiff')->name('report.inventory-diff');
        Route::get('report/action', 'ReportController@action')->name('report.action');
        Route::get('report/shop', 'ReportController@shop')->name('report.shop');
        Route::get('report/top', 'ReportController@top')->name('report.top');
        Route::get('report/quantity', 'ReportController@quantity')->name('report.quantity');
        Route::get('report/control', 'ReportController@control')->name('report.control');
    });

    // Category
    Route::get('category/import-{import}', 'CategoryController@import')->name('category.import');
    Route::resource('category', 'CategoryController');

    // User
    Route::get('user/report-settings/{report}', 'UserController@reportSettings')->name('user.reportSettings');
    Route::post('user/save-report-settings', 'UserController@saveReportSettings')->name('user.saveReportSettings');
    Route::resource('user', 'UserController');
    Route::resource('user_group', 'UserGroupController');

    // Plan
    Route::get('plan', 'PlanController@index')->name('plan.index');
    Route::get('plan/shop-{shop}', 'PlanController@shop')->name('plan.shop');
    Route::get('plan/plan-{plan}', 'PlanController@plan')->name('plan.plan');
    Route::post('plan/store', 'PlanController@store')->name('plan.store');
    Route::put('plan/update-plan-days/{shop_id}', 'PlanController@updatePlanDays')->name('plan.updatePlanDays');
    Route::put('plan/update-plan-products/{plan}', 'PlanController@updatePlanProducts')->name('plan.updatePlanProducts');
    Route::post('plan/update/{plan}', 'PlanController@update')->name('plan.update');
    Route::get('plan/copy/{plan}', 'PlanController@copy')->name('plan.copy');
    Route::delete('plan/delete/{plan}', 'PlanController@delete')->name('plan.delete');
    Route::get('plan-api/get-{plan}', 'PlanController@getPlan');

    // Shift
    Route::get('shift', 'ShiftController@index')->name('shift.index');
    Route::get('shift/shop-{shop}', 'ShiftController@shop')->name('shift.shop')->middleware('can:view,shop');
    Route::get('shift/open-{shop}', 'ShiftController@open')->name('shift.open')->middleware(['can:view,shop', 'can:open,shop']);
    Route::get('shift/close-{shift}', 'ShiftController@close')->name('shift.close')->middleware(['can:close,shift']);
    Route::get('shift/enter-{shop}', 'ShiftController@enter')->name('shift.enter')->middleware(['can:view,shop', 'can:enter,shop']);
    Route::get('shift/exit-{shop}', 'ShiftController@exit')->name('shift.exit')->middleware(['can:view,shop', 'can:enter,shop']);
    Route::get('shift/view-{shift}', 'ShiftController@view')->name('shift.view')->middleware('can:view,shift');
    Route::get('shift/inventory-{shift}', 'ShiftController@inventory')->name('shift-inventory.view')->middleware(['can:view,shift', 'can:inventory,shift']);

    // StoreHouse5
    Route::resource('waybills', 'ViewWaybillsController');
    Route::post('waybills/unload/', 'ViewWaybillsController@unload')->name('waybills.unload');
    Route::get('corrs/setting-{setting}', 'ViewCorrController@setting')->name('corrs.setting');
    Route::resource('corrs', 'ViewCorrController');
    Route::get('departs/setting-{setting}', 'ViewDepartController@setting')->name('departs.setting');
    Route::resource('departs', 'ViewDepartController');
    Route::resource('settings', 'ViewSettingsController');
    Route::get('settings/connect/{setting_id}', 'ViewSettingsController@connect')->name('settings.connect');
    Route::resource('setting_groups', 'ViewSettingGroupController');

    // Api
    Route::group([
        'middleware' => 'can:view,shift',
        'namespace'  => 'Api'
    ], function () {
        // Shift
        Route::get('shift-api/get-{shift}', 'ShiftController@getShift');
        Route::put('shift-api/set-status-{shift}', 'ShiftController@setStatus');
        Route::put('shift-api/set-quantity-{shift}', 'ShiftController@setQuantity');
        Route::put('shift-api/add-product-{shift}', 'ShiftController@addProduct');
        Route::put('shift-api/accept-product-{shift}', 'ShiftController@acceptProduct');
        Route::put('shift-api/add-wrong-product-{shift}', 'ShiftController@addWrongProduct');
        Route::put('shift-api/remove-wrong-product-{shift}', 'ShiftController@removeWrongProduct');

        // Movement
        Route::put('movement-api/add-{shift}', 'MovementController@addMovement');
        Route::put('movement-api/accept-{shift}', 'MovementController@acceptMovement');

        // Reject
        Route::get('reject-api/get-{shift}', 'RejectController@getRejects');
        Route::put('reject-api/add-{shift}', 'RejectController@addReject');

        // Inventory
        Route::get('inventory-api/get-{shift}', 'InventoryController@getInventory');
        Route::put('inventory-api/add-{shift}', 'InventoryController@addInventory');
    });

    // System
    Route::group([
        'namespace'  => 'System'
    ], function () {
        // Shift
        Route::get('system/shift', 'ShiftController@index')->name('system.shift');
        Route::post('system/shift/update', 'ShiftController@update')->name('system.shift.update');

        // Inventory
        Route::get('system/inventory/view-{inventory}', 'InventoryController@index')->name('system.inventory');
        Route::post('system/inventory/update', 'ShiftController@update')->name('system.inventory.update');
    });

    // StoreHouse5
    Route::group([
        'middleware' => ['auth'],
        'namespace'  => 'Api'
    ], function () {
         Route::post('sh5/get-corrs', 'StoreHouse5\\ApiCorrController@apiCorrs');
         Route::post('sh5/get-departs', 'StoreHouse5\\ApiDepartController@apiDeparts');
         Route::post('sh5/post-products', 'StoreHouse5\\ApiProductController@apiProduct');
         Route::get('sh5/get-products-group', 'StoreHouse5\\ApiProductGroupController@getGroups');
         Route::post('sh5/check-connect', 'StoreHouse5\\ApiCheckConnectController@checkConnect');
    });

    // Code
    Route::get('code', 'CodeController@index')->name('code.index');
    Route::post('code/update', 'CodeController@update')->name('code.update');

    // Reject
    Route::get('reject', 'RejectController@index')->name('reject.index');
    Route::get('reject/view-{reject}', 'RejectController@view')->name('reject.view');

    // Inventory
    Route::get('inventory', 'InventoryController@index')->name('inventory.index');
    Route::get('inventory/view-{inventory}', 'InventoryController@view')->name('inventory.view');

    // Movement
    Route::get('movement', 'MovementController@index')->name('movement.index');
    Route::get('movement/view-{movement}', 'MovementController@view')->name('movement.view');

    // Setting
    Route::get('setting', 'SettingController@index')->name('setting.index');
    Route::post('setting/update', 'SettingController@update')->name('setting.update');
});

Route::group(['namespace' => 'Cron'], function () {
    Route::get('shift-cron', 'ShiftController@index');
    Route::get('qty-cron', 'QuantityController@index');
    Route::get('import-cron', 'ImportController@index');
});

app/Http/Controllers/Api/StoreHouse5/ApiCheckConnectController.php
<?php

namespace App\Http\Controllers\Api\StoreHouse5;

use Illuminate\Http\Request;

use App\Http\Controllers\StoreHouse5\StoreHouse5Controller;

class ApiCheckConnectController extends StoreHouse5Controller
{
  // Метод проверки подключения к серверу StoreHouse5
  public function checkConnect(Request $request) {

    $response = "";

    if(isset($request)) {

        $ip = $request["ip"];
        $port = $request["port"];
        $username = $request["username"];
        $password = $request["password"];

        $StoreHouse5 = new StoreHouse5Controller();

        $request = $StoreHouse5->SH5_CONNECT($ip.":"."$port"."/api/sh5info", $username, $password, '', array());

        if ($request["errorCode"] === 0) {

        $response = "OK";

        } else {

        $error_file = 'StoreHouse5.logs.txt';
        $error = fopen($error_file, 'a+');
        fwrite($error, "Ошибка соединения со StoreHouse5 errMessage: ".$array["errMessage"].PHP_EOL);
        fclose($error);

        $response = "ERROR!";

        }

    }
    return $response;
  }
  
}

app/Http/Controllers/Api/StoreHouse5/ApiCorrController.php
<?php

namespace App\Http\Controllers\Api\StoreHouse5;

use App\Sh5Corr;

use App\Sh5Setting;

use Illuminate\Http\Request;

use App\Http\Controllers\StoreHouse5\StoreHouse5Controller;

class ApiCorrController extends StoreHouse5Controller
{
    // Метод получения списка складов
    public function apiCorrs(Request $request) {

        $response = "";

        $settings = Sh5Setting::where('id', '=', intval($request->all()["setting_id"]))->get();
        
        foreach($settings as $setting) {

            $response = $this->getCorrs($setting);

        }

        return $response;

    }

    public function getCorrs($setting) {

        $response = "";

        $StoreHouse5 = new StoreHouse5Controller();
        
        $request = $StoreHouse5->SH5_CONNECT($setting->ip.":"."$setting->port"."/api/sh5exec", $setting->username, $setting->password, 'Corrs', array());

        if ($request["errorCode"] === 0) {

            $response = $request["errMessage"];

            $request = array(
                'rid' => $request['shTable'][1]['values'][0],
                'guid' => $request['shTable'][1]['values'][1],
                'name' => $request['shTable'][1]['values'][5],
            );

            $db_guids = Sh5Corr::pluck('guid');

            $array_db_guid = array();

            foreach($db_guids as $db_guid) {

                array_push($array_db_guid, $db_guid);

            }

            // update
            $array_diff = array_diff($request["guid"], $array_db_guid);
            
            foreach($array_diff as $key => $guid) {
                
                if ($request["guid"][$key] != NULL) {

                    Sh5Corr::updateOrCreate(
                        [
                            'rid'     => $request['rid'][$key],
                            'name' => $request['name'][$key],
                            'guid'     => $request['guid'][$key],
                            'setting_id' => $setting->id,
                        ]
                    );

                } else {

                    continue;

                }
            }

            // delete
            $array_diff = array_diff($array_db_guid, $request["guid"]);
            
            foreach($array_diff as $key => $guid) {

                Sh5Corr::where('guid', '=', $guid)->where('setting_id', '=', $setting->id)->delete();
                
            }

        } else {

            $error_file = 'StoreHouse5.logs.txt';
            $error = fopen($error_file, 'a+');
            fwrite($error, "Ошибка подгрузки корреспондентов из StoreHouse5 errMessage: ".$array["errMessage"].PHP_EOL);
            fclose($error);

            $response = $request["errMessage"];

        }

        return $response;
    }
}

app/Http/Controllers/Api/StoreHouse5/ApiDepartController.php
<?php

namespace App\Http\Controllers\Api\StoreHouse5;

use App\Sh5Depart;

use App\Sh5Setting;

use Illuminate\Http\Request;

use App\Http\Controllers\StoreHouse5\StoreHouse5Controller;

class ApiDepartController extends StoreHouse5Controller
{
    // Метод получения список складов
    public function apiDeparts(Request $request) {

        $response = "";

        $settings = Sh5Setting::where('id', '=', intval($request->all()["setting_id"]))->get();
        
        foreach($settings as $setting) {

            $response = $this->getDeparts($setting);

        }
        
        return $response;

    }

     public function getDeparts($setting) {

        $response = "";

        $StoreHouse5 = new StoreHouse5Controller();

        $request = $StoreHouse5->SH5_CONNECT($setting->ip.":"."$setting->port"."/api/sh5exec", $setting->username, $setting->password, 'Departs', array());

        if ($request["errorCode"] === 0) {

            $response = $request["errMessage"];

            $request = array(
                'rid' => $request['shTable'][1]['values'][0],
                'guid' => $request['shTable'][1]['values'][1],
                'name' => $request['shTable'][1]['values'][2],
            );

            $db_guids = Sh5Depart::pluck('guid');

            $array_db_guid = array();

            foreach($db_guids as $db_guid) {

                array_push($array_db_guid, $db_guid);

            }

            // update
            $array_diff = array_diff($request["guid"], $array_db_guid);

            foreach($array_diff as $key => $guid) {

                if ($request["guid"][$key] != NULL) {

                    Sh5Depart::updateOrCreate(
                        [
                            'rid'     => $request['rid'][$key],
                            'name' => $request['name'][$key],
                            'guid'     => $request['guid'][$key],
                            'setting_id' => $setting->id,
                        ]
                    );

                } else {

                    continue;

                }
            }

            // delete
            $array_diff = array_diff($array_db_guid, $request["guid"]);

            foreach($array_diff as $key => $guid) {

                Sh5Depart::where('guid', '=', $guid)->where('setting_id', '=', $setting->id)->delete();

            }

        } else {

            $error_file = 'StoreHouse5.logs.txt';
            $error = fopen($error_file, 'a+');
            fwrite($error, "Ошибка подгрузки складов из StoreHouse5 errMessage: ".$array["errMessage"].PHP_EOL);
            fclose($error);

            $response = $request["errMessage"];

        }

        return $response;

    }

}

app/Http/Controllers/StoreHouse5/StoreHouse5Controller.php
<?php

namespace App\Http\Controllers\StoreHouse5;

use App\Http\Controllers\Controller;

use App\Product;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;


class StoreHouse5Controller extends Controller {

  // Метод коннекта к StoreHouse5
  protected function SH5_CONNECT($url, $username, $password="", $procName, $param=false){
    // if(strpos(" ".$_SERVER['HTTP_HOST'], "localhost")>0){
    //     // тогда оставляем как есть, т.к. на локалке сторхауз есть
    // }else{
    //     $url = str_replace('127.0.0.1','85.95.183.21',$url);
    // }
    if(!$url) return false;
    
    if(!$procName) $procName = 'NoProcedureName';
    
    $data = json_encode( array( "UserName"=>$username, "Password"=>$password, "procName"=>$procName ,"Input" => $param ) );  

    $ch = curl_init($url);

    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_ENCODING, "");
    curl_setopt($ch, CURLOPT_MAXREDIRS, 10);
    curl_setopt($ch, CURLOPT_TIMEOUT, 0);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, false);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type:application/json') );    
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $html = curl_exec($ch);
    
    curl_close($ch);        
    $array = json_decode($html,true);

    return $array;
  }

}

?>

app/Http/Controllers/StoreHouse5/ViewControllers/ViewSettingGroupController.php
<?php

namespace App\Http\Controllers;

use App\Sh5SettingGroup;
use App\Sh5Setting;

class ViewSettingGroupController extends Controller
{
    public function index()
    {
        return view('storehouse5/setting_groups.index', [
            'groups' => Sh5SettingGroup::all(),
            'settings' => Sh5Setting::all()
        ]);
    }

}

resources/views/storehouse5/waybills/form.blade.php
@extends('layouts.form')

@section('title', $waybill->number ?? 'Редактирование товарной накладной')
@section('action', $action)

@section('button')
    <div class="btn-group" role="group">
        <form action="{{route('waybills.unload')}}" method="post" id="form">
            {{csrf_field()}}
            <input type="hidden" name="id" value="{{$waybill->id}}">
            <input type="hidden" id="double_corr" name="corr_rid" value="{{$waybill->corr_rid}}">
            <input type="hidden" id="double_depart" name="depart_rid" value="{{$waybill->depart_rid}}">
            <input type="submit" class="btn btn-primary mr-4" value="Выгрузить накладную повторно">
        </form>
        <a class="btn btn-primary" href="#" onclick="$('#form').submit(); return false;"><i class="fa fa-save"></i></a>
        <a class="btn btn-secondary" href="{{route('waybills.index')}}"><i class="fa fa-reply"></i></a>
    </div>
@endsection

@section('form')
    @if (isset($group->id))
        {{method_field('PUT')}}
    @endif
    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label text-right">Название:</label>
        <div class="col-sm-10">
            <input type="text"
                   class="form-control {{$errors->has('number') ? 'is-invalid' : ''}}"
                   name="name"
                   id="name"
                   disabled
                   value="{{old('number', $waybill->number ?? '')}}">
            @if ($errors->has('number'))
                <div class="invalid-feedback">{{$errors->first('number')}}</div>
            @endif
        </div>
    </div>
    <div class="form-group row">
        <label for="shop_name" class="col-sm-2 col-form-label text-right">Смена:</label>
        <div class="col-sm-10">
            <input type="text"
                   class="form-control {{$errors->has('shop_name') ? 'is-invalid' : ''}}"
                   name="shop_name"
                   id="shop_name"
                   disabled
                   value="{{sprintf('%s (%s - %s)', $waybill->shift_id, $waybill->date_start, $waybill->date_end)}}">
            @if ($errors->has('shop_name'))
                <div class="invalid-feedback">{{$errors->first('shop_name')}}</div>
            @endif
        </div>
    </div>
    <div class="form-group row">
        <label for="corr_guid_cash" class="col-sm-2 col-form-label text-right">Корреспондент / Склад:</label>
        <div class="col-sm-10">
            <select onfocus="double_corr.value = this.value" onblur="double_corr.value = this.value" class="form-control" id="corr_rid">
                <option value="0" selected >-</option>
                @if($waybill->corr_rid < 10000)
                    @foreach($corrs as $corr)
                        @if($corr->setting_id === $waybill->setting_id)
                            <option value="{{$corr->rid}}" {{($waybill->corr_rid === $corr->rid && $waybill->corr_rid != 0) ? 'selected' : ''}}>{{$corr->name}}</option>
                        @endif
                    @endforeach
                @else
                    @foreach($departs as $depart)
                        @if($depart->setting_id === $waybill->setting_id)
                            <option value="{{$depart->rid}}" {{($waybill->corr_rid === $depart->rid) ? 'selected' : ''}}>{{$depart->name}}</option>
                        @endif
                    @endforeach
                @endif
            </select>
        </div>
    </div>
    <div class="form-group row">
        <label for="depart_guid" class="col-sm-2 col-form-label text-right">Склад:</label>
        <div class="col-sm-10">
            <select onfocus="double_depart.value = this.value" onblur="double_depart.value = this.value"  name="depart_rid" class="form-control" id="depart_rid">
                <option value="0" selected >-</option>
                @foreach($departs as $depart)
                    @if($depart->setting_id === $waybill->setting_id)
                        <option value="{{$depart->rid}}" {{($waybill->depart_rid === $depart->rid) ? 'selected' : ''}}>{{$depart->name}}</option>
                    @endif
                @endforeach
            </select>
        </div>
    </div>
    <div class="card-header">
        <div class="float-left">
            <div class="h3">Товары</div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th>#</th>
            <th>Название</th>
            <th>Цена</th>
            <th>Сумма</th>
            <th>Количество / КГ</th>
            <th class="text-right">Редактировать</th>
        </tr>
        </thead>
        <tbody>
        @forelse ($products as $product)
            <tr>
                <td>{{$product->product_id}}</td>
                <td>
                    {{$product->name}}
                    <div class="small text-muted">{{$product->guid}}</div>
                </td>
                <td>@format($product->price)</td>
                <td>{{ $product->amount }} ₽</td>
                <td>{{ number_format($product->quantity, 2) }}</td>
                <td class="text-right">
                    <a class="btn btn-primary btn-sm" href="{{route('product.edit', ['id' => $product->product_id])}}">
                        <i class="fa fa-pen"></i>
                    </a>
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="3">Пусто</td>
            </tr>
        @endforelse
        </tbody>
    </table>
@endsection

resources/views/storehouse5/waybills/index.blade.php
@extends('layouts.list')

@section('title', 'Товарные накладные')

@section('button')
    <push-sh5-waybills-component></push-sh5-waybills-component>
@endsection
@section('list')
    <table class="table">
        <thead>
        <tr>
            <th>#</th>
            <th>Номер</th>
            <th>Склад</th>
            <th>Контрагент / Склад</th>
            <th>Дата</th>
            <th>#</th>
        </tr>
        </thead>
        <tbody>
            @forelse ($waybills as $waybill)
                <tr>
                    <td>{{$waybill->id}}</td>
                    <td>
                        {{$waybill->number}}
                        <div class="small text-muted">{{$waybill->guid}}</div>
                    </td>
                    @foreach($departs as $depart)
                        @if($depart->rid === $waybill->depart_rid && $depart->setting_id === $waybill->setting_id)
                            <td>{{ $depart->name }}</td>
                        @endif
                    @endforeach
                    @if($waybill->corr_rid === 0)
                            <td>-</td>
                    @else
                        @foreach($corrs as $corr)
                            @if($corr->rid === $waybill->corr_rid && $corr->setting_id === $waybill->setting_id)
                                <td>{{ $corr->name }}</td>
                            @endif
                        @endforeach
                    @endif
                    @foreach($departs as $depart)
                        @if($depart->rid === $waybill->corr_rid && $depart->setting_id === $waybill->setting_id)
                            <td>{{ $depart->name }}</td>
                        @endif
                    @endforeach
                    <td>{{$waybill->created_at}}</td>
                    <td>
                        <a class="btn btn-primary btn-sm" href="{{route('waybills.edit', ['id' => $waybill->id])}}">
                            <i class="fa fa-pen"></i>
                        </a>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="3">Пусто</td>
                </tr>
            @endforelse
        </tbody>
    </table>
@endsection