routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes([
    'register' => false,
    'reset'    => false,
    'verify'   => false
]);

Route::group(['middleware' => ['auth']], function() {
    // Product
    Route::get('product/json', 'ProductController@json');
    Route::get('product/import-{import}', 'ProductController@import')->name('product.import');
    Route::resource('product', 'ProductController');

    // Franchise
    Route::resource('franchise', 'FranchiseController');

    // Import
    Route::resource('import', 'ImportController');

    // Shop
    Route::get('shop', 'ShopController@index')->name('shop.index');
    Route::get('shop/json', 'ShopController@json')->name('product.json');
    Route::resource('shop', 'ShopController');

    // Device
    Route::get('device', 'DeviceController@index')->name('device.index');
    Route::resource('device', 'DeviceController');



    Route::group(['middleware' => ['checkReport']], function() {
        // Report
        Route::get('report/order', 'ReportController@order')->name('report.order');
        Route::get('report/shift', 'ReportController@shift')->name('report.shift');
        Route::get('report/shift-user', 'ReportController@shiftUser')->name('report.shift-user');
        Route::get('report/shift-plan', 'ReportController@shiftPlan')->name('report.shift-plan');
        Route::get('report/reject', 'ReportController@reject')->name('report.reject');
        Route::get('report/quality', 'ReportController@quality')->name('report.quality');
        Route::get('report/inventory', 'ReportController@inventory')->name('report.inventory');
        Route::get('report/inventory-kitchen', 'ReportController@inventoryKitchen')->name('report.inventory-kitchen');
        Route::get('report/inventory-diff', 'ReportController@inventoryDiff')->name('report.inventory-diff');
        Route::get('report/action', 'ReportController@action')->name('report.action');
        Route::get('report/shop', 'ReportController@shop')->name('report.shop');
        Route::get('report/top', 'ReportController@top')->name('report.top');
        Route::get('report/quantity', 'ReportController@quantity')->name('report.quantity');
        Route::get('report/control', 'ReportController@control')->name('report.control');
    });

    // Category
    Route::get('category/import-{import}', 'CategoryController@import')->name('category.import');
    Route::resource('category', 'CategoryController');

    // User
    Route::get('user/report-settings/{report}', 'UserController@reportSettings')->name('user.reportSettings');
    Route::post('user/save-report-settings', 'UserController@saveReportSettings')->name('user.saveReportSettings');
    Route::resource('user', 'UserController');
    Route::resource('user_group', 'UserGroupController');

    // Plan
    Route::get('plan', 'PlanController@index')->name('plan.index');
    Route::get('plan/shop-{shop}', 'PlanController@shop')->name('plan.shop');
    Route::get('plan/plan-{plan}', 'PlanController@plan')->name('plan.plan');
    Route::post('plan/store', 'PlanController@store')->name('plan.store');
    Route::put('plan/update-plan-days/{shop_id}', 'PlanController@updatePlanDays')->name('plan.updatePlanDays');
    Route::put('plan/update-plan-products/{plan}', 'PlanController@updatePlanProducts')->name('plan.updatePlanProducts');
    Route::post('plan/update/{plan}', 'PlanController@update')->name('plan.update');
    Route::get('plan/copy/{plan}', 'PlanController@copy')->name('plan.copy');
    Route::delete('plan/delete/{plan}', 'PlanController@delete')->name('plan.delete');
    Route::get('plan-api/get-{plan}', 'PlanController@getPlan');

    // Shift
    Route::get('shift', 'ShiftController@index')->name('shift.index');
    Route::get('shift/shop-{shop}', 'ShiftController@shop')->name('shift.shop')->middleware('can:view,shop');
    Route::get('shift/open-{shop}', 'ShiftController@open')->name('shift.open')->middleware(['can:view,shop', 'can:open,shop']);
    Route::get('shift/close-{shift}', 'ShiftController@close')->name('shift.close')->middleware(['can:close,shift']);
    Route::get('shift/enter-{shop}', 'ShiftController@enter')->name('shift.enter')->middleware(['can:view,shop', 'can:enter,shop']);
    Route::get('shift/exit-{shop}', 'ShiftController@exit')->name('shift.exit')->middleware(['can:view,shop', 'can:enter,shop']);
    Route::get('shift/view-{shift}', 'ShiftController@view')->name('shift.view')->middleware('can:view,shift');
    Route::get('shift/inventory-{shift}', 'ShiftController@inventory')->name('shift-inventory.view')->middleware(['can:view,shift', 'can:inventory,shift']);

    // StoreHouse5
    Route::resource('waybills', 'ViewWaybillsController');
    Route::post('waybills/unload/', 'ViewWaybillsController@unload')->name('waybills.unload');
    Route::get('corrs/setting-{setting}', 'ViewCorrController@setting')->name('corrs.setting');
    Route::resource('corrs', 'ViewCorrController');
    Route::get('departs/setting-{setting}', 'ViewDepartController@setting')->name('departs.setting');
    Route::resource('departs', 'ViewDepartController');
    Route::resource('settings', 'ViewSettingsController');
    Route::get('settings/connect/{setting_id}', 'ViewSettingsController@connect')->name('settings.connect');
    Route::resource('setting_groups', 'ViewSettingGroupController');

    // Api
    Route::group([
        'middleware' => 'can:view,shift',
        'namespace'  => 'Api'
    ], function () {
        // Shift
        Route::get('shift-api/get-{shift}', 'ShiftController@getShift');
        Route::put('shift-api/set-status-{shift}', 'ShiftController@setStatus');
        Route::put('shift-api/set-quantity-{shift}', 'ShiftController@setQuantity');
        Route::put('shift-api/add-product-{shift}', 'ShiftController@addProduct');
        Route::put('shift-api/accept-product-{shift}', 'ShiftController@acceptProduct');
        Route::put('shift-api/add-wrong-product-{shift}', 'ShiftController@addWrongProduct');
        Route::put('shift-api/remove-wrong-product-{shift}', 'ShiftController@removeWrongProduct');

        // Movement
        Route::put('movement-api/add-{shift}', 'MovementController@addMovement');
        Route::put('movement-api/accept-{shift}', 'MovementController@acceptMovement');

        // Reject
        Route::get('reject-api/get-{shift}', 'RejectController@getRejects');
        Route::put('reject-api/add-{shift}', 'RejectController@addReject');

        // Inventory
        Route::get('inventory-api/get-{shift}', 'InventoryController@getInventory');
        Route::put('inventory-api/add-{shift}', 'InventoryController@addInventory');
    });

    // System
    Route::group([
        'namespace'  => 'System'
    ], function () {
        // Shift
        Route::get('system/shift', 'ShiftController@index')->name('system.shift');
        Route::post('system/shift/update', 'ShiftController@update')->name('system.shift.update');

        // Inventory
        Route::get('system/inventory/view-{inventory}', 'InventoryController@index')->name('system.inventory');
        Route::post('system/inventory/update', 'ShiftController@update')->name('system.inventory.update');
    });

    // StoreHouse5
    Route::group([
        'middleware' => ['auth'],
        'namespace'  => 'Api'
    ], function () {
         Route::post('sh5/get-corrs', 'StoreHouse5\\ApiCorrController@apiCorrs');
         Route::post('sh5/get-departs', 'StoreHouse5\\ApiDepartController@apiDeparts');
         Route::post('sh5/post-products', 'StoreHouse5\\ApiProductController@apiProduct');
         Route::get('sh5/get-products-group', 'StoreHouse5\\ApiProductGroupController@getGroups');
         Route::post('sh5/check-connect', 'StoreHouse5\\ApiCheckConnectController@checkConnect');
    });

    // Code
    Route::get('code', 'CodeController@index')->name('code.index');
    Route::post('code/update', 'CodeController@update')->name('code.update');

    // Reject
    Route::get('reject', 'RejectController@index')->name('reject.index');
    Route::get('reject/view-{reject}', 'RejectController@view')->name('reject.view');

    // Inventory
    Route::get('inventory', 'InventoryController@index')->name('inventory.index');
    Route::get('inventory/view-{inventory}', 'InventoryController@view')->name('inventory.view');

    // Movement
    Route::get('movement', 'MovementController@index')->name('movement.index');
    Route::get('movement/view-{movement}', 'MovementController@view')->name('movement.view');

    // Setting
    Route::get('setting', 'SettingController@index')->name('setting.index');
    Route::post('setting/update', 'SettingController@update')->name('setting.update');
});

Route::group(['namespace' => 'Cron'], function () {
    Route::get('shift-cron', 'ShiftController@index');
    Route::get('qty-cron', 'QuantityController@index');
    Route::get('import-cron', 'ImportController@index');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $guarded = [];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function group()
    {
        return $this->belongsTo('App\UserGroup');
    }

    public function getGroupMenuItems()
    {
        return $this->group ? (array)unserialize($this->group->menu) : [];
    }

    public function shopsVisible()
    {
        return $this->belongsToMany('App\Shop', 'user_shop')->wherePivot('type', 'visible')->withPivot('time');
    }

    public function shopsStock()
    {
        return $this->belongsToMany('App\Shop', 'user_shop')->wherePivot('type', 'stock');
    }

    public function reportSettings($report)
    {
        return $this->hasOne('App\ReportSetting')->where('report', $report)->get()->first();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\ReportSetting;
use App\Shop;
use App\User;
use App\UserGroup;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public const PASSWORD = 'password';

    public function index()
    {
        return view('user.index', [
            'users' => User::with('group')->get()
        ]);
    }

    public function create()
    {
        return view('user.form', [
            'user'         => '',
            'groups'       => UserGroup::all(),
            'shops'        => Shop::all(),
            'shopsVisible' => old('shops_visible', []),
            'shopsStock'   => old('shops_stock', []),
            'action'       => route('user.store')
        ]);
    }

    public function store(Request $request)
    {
        Validator::make($request->all(), [
            'name' => [
                'required',
                'max:255',
                'unique:users'
            ],
            'code' => [
                'required',
                'min:6',
                'unique:users'
            ]
        ])->validate();

        $user = User::create([
            'group_id' => $request->post('group_id'),
            'name'     => $request->post('name'),
            'email'    => sprintf('%s@mail.ru', $request->post('code')),
            'code'     => $request->post('code'),
            'password' => Hash::make(self::PASSWORD)
        ]);

        $this->addShops($user);

        return redirect()
            ->route('user.index')
            ->with('success', 'Пользователь успешно добавлен');
    }

    public function edit(User $user)
    {
        $shopsTime = [];

        $user->shopsVisible()->each(function ($item) use (&$shopsTime) {
            $shopsTime[$item->pivot->shop_id] = $item->pivot->time;
        });

        return view('user.form', [
            'user'         => $user,
            'groups'       => UserGroup::all(),
            'shops'        => Shop::all(),
            'shopsVisible' => $user->shopsVisible()->pluck('shop_id')->toArray(),
            'shopsTime'    => $shopsTime,
            'shopsStock'   => $user->shopsStock()->pluck('shop_id')->toArray(),
            'action'       => route('user.update', ['id' => $user->id])
        ]);
    }

    public function update(Request $request, User $user)
    {
        Validator::make($request->all(), [
            'name' => [
                'required',
                'max:255',
                Rule::unique('users')->ignore($user->id),
            ],
            'code' => [
                'required',
                'min:6',
                Rule::unique('users')->ignore($user->id),
            ]
        ])->validate();

        $user->group_id = $request->post('group_id');
        $user->name = $request->post('name');
        $user->code = $request->post('code');
        $user->password = Hash::make(self::PASSWORD);
        $user->save();

        $this->addShops($user);

        return redirect()
            ->route('user.index')
            ->with('success', 'Пользователь успешно обновлен');
    }

    private function addShops($user)
    {
        DB::table('user_shop')->where('user_id', $user->id)->delete();

        if (request()->has('shops_visible')) {
            foreach (request()->post('shops_visible') as $shop_id) {
                DB::table('user_shop')->insert([
                    'user_id' => $user->id,
                    'shop_id' => $shop_id,
                    'type'    => 'visible',
                    'time'    => request()->input('shops_time.' . $shop_id)
                ]);
            }
        }

        if (request()->has('shops_stock')) {
            foreach (request()->post('shops_stock') as $shop_id) {
                DB::table('user_shop')->insert([
                    'user_id' => $user->id,
                    'shop_id' => $shop_id,
                    'type'    => 'stock'
                ]);
            }
        }
    }

    public function reportSettings($report)
    {
        $settings = Auth::user()->reportSettings($report);

        return view('user.report-settings', [
            'report'         => $report,
            'categories'     => Category::all()->prepend((object)[
                'id'   => 0,
                'name' => 'Без категории'
            ]),
            'userCategories' => isset($settings->settings['categories']) ? $settings->settings['categories'] : []
        ]);
    }

    public function saveReportSettings()
    {
        ReportSetting::updateOrCreate([
            'user_id' => Auth::user()->id,
            'report'  => request()->report
        ], [
            'settings' => request()->only(['categories'])
        ]);

        return redirect()->route('report.' . request()->report);
    }
}

resources/views/user/form.blade.php
@extends('layouts.form')

@section('title', $user->name ?? 'Добавление пользователя')
@section('action', $action)

@section('button')
    <div class="btn-group" role="group">
        <a class="btn btn-primary" href="#" onclick="$('#form').submit(); return false;"><i class="fa fa-save"></i></a>
        <a class="btn btn-secondary" href="{{route('user.index')}}"><i class="fa fa-reply"></i></a>
    </div>
@endsection

@section('form')
    @if (isset($user->id))
        {{method_field('PUT')}}
    @endif
    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label text-right">Имя:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control {{$errors->has('name') ? 'is-invalid' : ''}}" name="name" id="name"
                   value="{{old('name', $user->name ?? '')}}">
            @if ($errors->has('name'))
                <div class="invalid-feedback">{{$errors->first('name')}}</div>
            @endif
        </div>
    </div>
    <div class="form-group row">
        <label for="code" class="col-sm-2 col-form-label text-right">Пин-код:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control {{$errors->has('code') ? 'is-invalid' : ''}}" name="code" id="code"
                   value="{{old('code', $user->code ?? '')}}">
            @if ($errors->has('code'))
                <div class="invalid-feedback">{{$errors->first('code')}}</div>
            @endif
        </div>
    </div>
    <div class="form-group row">
        <label for="group" class="col-sm-2 col-form-label text-right">Группа:</label>
        <div class="col-sm-10">
            <select class="form-control" name="group_id" id="group">
                @foreach($groups as $group)
                    <option value="{{$group->id}}" {{($group->id == old('group_id', $user->group_id ?? '')) ? 'selected' : ''}}>{{$group->name}}</option>
                @endforeach
            </select>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label text-right">Рабочие магазины:</label>
        <div class="col-sm-10">
            <div class="list-group">
                @foreach($shops as $s)
                    <div class="list-group-item">
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox"
                                   class="custom-control-input"
                                   id="visible-{{$s->id}}"
                                   name="shops_visible[]"
                                   value="{{$s->id}}"
                                   {{in_array($s->id, $shopsVisible) ? 'checked' : ''}}>
                            <label class="custom-control-label" for="visible-{{$s->id}}">{{$s->name}}</label>
                        </div>
                        <div class="form-group row mt-2">
                            <label for="time-{{$s->id}}" class="col-sm-2 col-form-label">Время работы</label>
                            <div class="col-sm-10">
                                <input type="text"
                                       class="form-control"
                                       name="shops_time[{{$s->id}}]"
                                       id="time-{{$s->id}}"
                                       value="{{old('shops_time[' . $s->id . ']', $shopsTime[$s->id] ?? '')}}">
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label text-right">Магазины с наличием:</label>
        <div class="col-sm-10">
            <div class="list-group">
                @foreach($shops as $s)
                    <div class="list-group-item">
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox"
                                   class="custom-control-input"
                                   id="stock-{{$s->id}}"
                                   name="shops_stock[]"
                                   value="{{$s->id}}"
                                   {{in_array($s->id, $shopsStock) ? 'checked' : ''}}
                            >
                            <label class="custom-control-label" for="stock-{{$s->id}}">{{$s->name}}</label>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.list')

@section('title', 'Пользователи')

@section('button')
    <div class="btn-group" role="group">
        <a href="{{route('user.create')}}" class="btn btn-primary"><i class="fa fa-plus"></i></a>
    </div>
@endsection

@section('list')
    <table class="table">
        <thead>
        <tr>
            <th width="1">#</th>
            <th>Пользователь</th>
            <th>Группа</th>
            <th>Пин-код</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @forelse ($users as $user)
            <tr>
                <td>{{$user->id}}</td>
                <td>{{$user->name}}</td>
                <td>{{$user->group ? $user->group->name : '-' }}</td>
                <td>{{$user->code }}</td>
                <td class="text-right">
                    <a class="btn btn-primary btn-sm" href="{{route('user.edit', ['id' => $user->id])}}">
                        <i class="fa fa-pen"></i>
                    </a>
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="5">Пусто</td>
            </tr>
        @endforelse
        </tbody>
    </table>
@endsection

resources/views/user/report-settings.blade.php
@extends('layouts.form')

@section('title', 'Настройки отчета')
@section('action', route('user.saveReportSettings'))

@section('button')
    <div class="btn-group" role="group">
        <a class="btn btn-primary" href="#" onclick="$('#form').submit(); return false;"><i class="fa fa-save"></i></a>
    </div>
@endsection

@section('form')
    <div class="form-group row">
        <label class="col-sm-2 col-form-label text-right">Категории товаров:</label>
        <div class="col-sm-10">
            <div class="list-group">
                @foreach($categories as $c)
                    <div class="list-group-item">
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox"
                                   class="custom-control-input"
                                   id="category-{{$c->id}}"
                                   name="categories[]"
                                   value="{{$c->id}}"
                                   {{in_array($c->id, $userCategories) ? 'checked' : ''}}
                            >
                            <label class="custom-control-label" for="category-{{$c->id}}">{{$c->name}}</label>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
    <input type="hidden" name="report" value="{{$report}}">
@endsection